### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by DavidCed** [mrporsev/DD2480#104]
"
Each LIC function needs a total of >= 3 tests. I recommend adding a negative (positive) test in case you have a positive (negative) test so far, and also a test with invalid input.
"

- [x] #105
- [x] #106
- [x] #107
- [x] #108
- [x] #109
- [x] #110
- [x] #111
- [x] #112
- [x] #113
- [x] #114
- [x] #115
- [x] #116
- [x] #117
- [x] #118
- [x] #119

**Comment by mrporsev** [comment]
Done
